title: Jekyll site using React + Weave
author: Eng @ Stitch Fix
email: eng@stitchfix.com
description: A Jekyll static site boilerplate for rapidly prototyping using React + Weave

twitter_username:
github_username: stitchfix

# Build settings
destination: public
source: src
baseurl: /jekyll-react

markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock','node_modules']
